### ISSUE TITLE
compiler errors

### ISSUE THREAD

**Issue by rajpaz** [Mironor/Play-2.0-Java-MongoDb-Jackson-exemple#2]
I am seeing following compiler errors.
I am new to Play,  so would appreciate any help in resolving this 
thanks

---

error: error while loading CharSequence, class file '/Library/Java/JavaVirtualMachines/jdk1.8.0_05.jdk/Contents/Home/jre/lib/rt.jar(java/lang/CharSequence.class)' is broken
(class java.lang.RuntimeException/bad constant pool tag 18 at byte 10)
error: error while loading Comparator, class file '/Library/Java/JavaVirtualMachines/jdk1.8.0_05.jdk/Contents/Home/jre/lib/rt.jar(java/util/Comparator.class)' is broken
(class java.lang.RuntimeException/bad constant pool tag 18 at byte 20)
error: error while loading AnnotatedElement, class file '/Library/Java/JavaVirtualMachines/jdk1.8.0_05.jdk/Contents/Home/jre/lib/rt.jar(java/lang/reflect/AnnotatedElement.class)' is broken
(class java.lang.RuntimeException/bad constant pool tag 18 at byte 76)
error: error while loading Arrays, class file '/Library/Java/JavaVirtualMachines/jdk1.8.0_05.jdk/Contents/Home/jre/lib/rt.jar(java/util/Arrays.class)' is broken
(class java.lang.RuntimeException/bad constant pool tag 18 at byte 755)
/var/folders/ss/xkb1y8qx1ts71wkfwppbyry00000gn/T/sbt_4fc482a5/xsbt/ExtractAPI.scala:489error: java.util.Comparator does not take type parameters
private[this] val sortClasses = new Comparator[Symbol] {
^
5 errors found
(compile:compile) Error compiling sbt component 'compiler-interface'

**Comment by Mironor** [comment]
Hi rajpaz,

did you change anything in the repo (especially the build.sbt file) on your local machine?

**Comment by rajpaz** [comment]
Hello...
thanks for responding. I did not change anything. 
Here is the build.sbt

name := "todoJava"
version := "1.0-SNAPSHOT"
scalaVersion := "2.10.0"
lazy val root = (project in file(".")).enablePlugins(PlayJava)
libraryDependencies ++= Seq(
  "net.vz.mongodb.jackson" %% "play-mongo-jackson-mapper" % "1.1.0"
)

**Comment by Mironor** [comment]
It seems that the problem is that you have jdk 1.8 and this repo works with scala 2.10 (as seen in build.sbt)

You should change the content of the build.sbt to:
```
name := "todoJava"

version := "1.0-SNAPSHOT"

scalaVersion := "2.11.1"

lazy val root = (project in file(".")).enablePlugins(PlayJava)

libraryDependencies ++= Seq(
  "net.vz.mongodb.jackson" % "play-mongo-jackson-mapper_2.10" % "1.1.0"
)

javaOptions in Test += "-Dconfig.file=conf/test.conf"
```

I also updated the repo, so you can just git pull it.

**Comment by rajpaz** [comment]
thanks... this seems to have fixed the compilation.
